### PR TITLE
Fix #99

### LINKED ISSUE #99: Check that 'png_filename' in 'create_map' is valid
Currently, `create_map` does not check if the `png_filename` is valid: it should be one word. Not a number, not NULL, not NA, not two or zero words.

Make `create_map` check if the `png_filename` is valid:

```r
test_that("check png_filename argument", {
  skip("Issue 99. Issue #99")
  expect_error(
    create_map(
      png_filename = 42
    ),
    "'png_filename' must be one word"
  )
  expect_error(
    create_map(
      png_filename = c("one filename", "too many")
    ),
    "'png_filename' must be one word"
  )
  expect_error(
    create_map(
      png_filename = NULL
    ),
    "'png_filename' must be one word"
  )
  expect_error(
    create_map(
      png_filename = c()
    ),
    "'png_filename' must be one word"
  )
  expect_error(
    create_map(
      png_filename = NA
    ),
    "'png_filename' must be one word"
  )
})
```

### PR DESCRIPTION
**Pull request by alexinedewit**

### CODE REVIEW

**Comment by alexinedewit** [comment]
I don't know how to solve the cyclomatic complexity.. Help!

**Comment by richelbilderbeek** [comment]
@alexinedewit it means the function has gotten too complex. You are not the only one to blame for this :grin: :+1:

```r
  if (is.numeric(png_filename) || is.na(png_filename) ||
      is.null(png_filename) || length(png_filename) != 1)
    stop("'png_filename' must be one word")
```

The cyclomatic complexity here is already 5: there are five ways the program can flow through the code:

 * first if is TRUE, do the if statement
 * first if is FALSE, second if is TRUE, do the if statement
 * first if is FALSE, second if is FALSE, third if is TRUE, do the if statement
 * first if is FALSE, second if is FALSE, third if is FALSE, fourth if is TRUE, do the if statement
 * first if is FALSE, second if is FALSE, third if is FALSE, fourth if is FALSE, skip the if statement

A solution is to write a function `check_png_filename`, so one can write `check_png_filename(png_filename)` within `create_map`. The function `check_png_filename` will only do the complex if statement.

You want to have a stab at this?

**Comment by alexinedewit** [comment]
Yes, pick me!

**Comment by richelbilderbeek** [comment]
@alexine: great, the work is yours :+1:

If you *really* want, I can create an Issue, but I'd say this suffices? If not, let me know!

Good luck adding that function :+1:

**Comment by AlexDaniel** [comment]
Hey, I'm the owner of @Alexine. I guess this was a wrong ping :) Have a nice day!

**Comment by richelbilderbeek** [comment]
I hope @alexinedewit will fix this today (i.e. Dec 1st) :+1:

**Pull request merged**
